### ISSUE TITLE
Node and Node connecting error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [theintencity/p2p-sip#12]
```
Network[1] bootstrap server= False neighbors= 0 candidates= 1
bootstrap trying node= <node ip='224.0.1.2' port=5062 type=1 
guid=560648175799974964474476133579132137349520581240L>
Network[1] sending 26 bytes 127.0.1.1:9080=>224.0.1.2:5062: <Message 
name=Discover:Request >
bootstrap did not receive response.
Network[1] bootstrap server= False neighbors= 0 candidates= 0
Network[1] bootstrap server= False neighbors= 0 candidates= 1
bootstrap trying node= <node ip='224.0.1.2' port=5062 type=1 
guid=560648175799974964474476133579132137349520581240L>
Network[1] sending 26 bytes 127.0.1.1:9080=>224.0.1.2:5062: <Message 
name=Discover:Request >
('192.168.1.25', 6857)=>('192.168.1.1', 5062) on type=2
ɠr▒':▒▒▒▒▒▒h@▒▒
Error in received message: No first line found
Traceback (most recent call last):
  File "/p2p-sip.r76/src/std/rfc3261.py", line 484, in received
    print data; m._parse(data)
  File "/p2p-sip.r76/src/std/rfc3261.py", line 253, in _parse
    except: raise ValueError, 'No first line found'
ValueError: No first line found

have any idea?
```

Original issue reported on code.google.com by `frt524...@gmail.com` on 3 Aug 2013 at 8:07

**Comment by GitMr** [comment]
Is this problem solved ??
